OnlineShop/urls.py
from django.contrib import admin
from django.urls import path, include
from webapp import urls
import webapp
from services import urls
import services
from blog import urls
import blog
from contact import urls
import contact
from shop import urls
import shop
from cart import urls
import cart
from authentication import urls
import authentication

urlpatterns = [
    path('admin/', admin.site.urls),
    path('services/', include(services.urls)),
    path('blog/', include(blog.urls)),
    path('contact/', include(contact.urls)),
    path('shop/', include(shop.urls)),
    path('cart/', include(cart.urls)),
    path('authentication/', include(authentication.urls)),
    path('', include(webapp.urls)),
]

blog/urls.py
from django.urls import path, include
from blog import views

urlpatterns = [
    path('', views.blog, name="Blog"),
    path('category/<int:category_id>', views.category, name="Category"),
]

cart/urls.py
from django.urls import path
from . import views

app_name = "cart"

urlpatterns = [
    path("add/<int:product_id>/", views.add_product, name="add"),
    path("remove/<int:product_id>/", views.remove_product, name="remove"),
    path("subtract/<int:product_id>/", views.subtract_product, name="subtract"),
    path("clean", views.clean_all_cart, name="clean"),
]

shop/urls.py
from django.urls import path
from shop import views

urlpatterns = [
    path('', views.shop, name="Shop"),
]

cart/models.py
from django.db import models

# Create your models here.

shop/models.py
from django.db import models

# Create your models here.

class ProductCategory(models.Model):
    name = models.CharField(max_length=50)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now_add=True)

    class Meta():
        verbose_name = "productcategory"
        verbose_name_plural = "productcategories"

    def __str__(self):
        return self.name
    

class Product(models.Model):
    name = models.CharField(max_length=50)
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="shop", null=True, blank=True)
    price = models.FloatField()
    availability = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now_add=True)

    class Meta():
        verbose_name = "product"
        verbose_name_plural = "products"

    def __str__(self):
        return self.name

cart/views.py
from django.shortcuts import render
from .cart import Cart
from shop.models import Product
from django.shortcuts import redirect

# Create your views here.

def add_product(request, product_id):
    cart = Cart(request)
    product = Product.objects.get(id=product_id)
    cart.add(product=product)
    return redirect("Shop")

def remove_product(request, product_id):
    cart = Cart(request)
    product = Product.objects.get(id=product_id)
    cart.remove(product=product)
    return redirect("Shop")

def subtract_product(request, product_id):
    cart=Cart(request)
    product = Product.objects.get(id=product_id)
    cart.subtract(product=product)
    return redirect("Shop")

def clean_all_cart(request):
    cart = Cart(request)
    cart.clean_cart()
    return redirect("Shop")

shop/views.py
from django.shortcuts import render
from .models import Product, ProductCategory

# Create your views here.

def shop(request):
    products = Product.objects.all()
    return render(request, "shop/shop.html", {"products": products})

shop/templates/cart/widget.html
<table class="table">
    <thead>
        <tr>
            <th colspan="3">Shopping Cart</th>
        </tr>
        <tr>
            <th>Product</th>
            <th>Quantity</th>
            <th>Price</th>
        </tr>
    </thead>
    <tbody>
        {% if request.session.cart.items %}
            {% for key, value in request.session.cart.items %}
                <tr>
                    <td>{{value.name}}</td>
                    <td>{{value.quantity}}
                        <a href="{% url 'cart:add' value.product_id %}" style="text-decoration: none; color: black;">+</a>
                        <a href="{% url 'cart:subtract' value.product_id %}" style="text-decoration: none; color: black;">-</a>
                    </td>
                    <td>
                        {{value.price}} €                        
                    </td>
                </tr>
            {% endfor %}
        {% else %}
            <tr>
                <td colspan="3">
                    <div>
                        No products selected
                    </div>
                </td>
            </tr>
        {% endif %}
    </tbody>
    <tfoot>
        <tr>
            <td><h4>Total: {{cart_total_import}} €</h4></td>
        </tr>
        {% if request.session.cart.items %}
        <tr>
            <td colspan="3"><a href="#" class="add_button" style="padding: 5px; border-radius: 7px;">Make an order</a></td>
        </tr>
        {% endif %}
    </tfoot>
</table>